# .github/workflows/reusable-docker-build-acr.yaml
name: Reusable Docker Build for ACR

on:
  workflow_call:
    inputs:
      image-name:
        description: 'samplevotingapp_result'
        required: true
        type: string
      tags:
        description: '（如 latest,v1.0）'
        required: false
        type: string
        default: 'latest'
      push:
        description: 'if push to ACR'
        required: false
        type: boolean
        default: false
      acr-registry:
        description: '阿里云 ACR 实例地址（如 registry.cn-hangzhou.aliyuncs.com）'
        required: true
        type: string
      acr-namespace:
        description: '阿里云 ACR 命名空间（通常是你的阿里云账号 ID 或自定义 namespace）'
        required: true
        type: string
      dockerfile:
        description: 'Dockerfile 路径（相对于仓库根目录）'
        required: false
        type: string
        default: './Dockerfile'
      context:
        description: 'Build context path'
        required: false
        type: string
        default: '.'
    secrets:
      ACR_REGISTRY_USER:
        required: true
      ACR_REGISTRY_PASSWORD:
        required: true
      SECURE_API_TOKEN:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Alibaba Cloud ACR
        if: ${{ inputs.push }}
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.acr-registry }}
          username: ${{ secrets.ACR_REGISTRY_USER }}
          password: ${{ secrets.ACR_REGISTRY_PASSWORD }}

      - name: Prepare tags
        id: tags
        run: |
          IFS=',' read -ra TAGS <<< "${{ inputs.tags }}"
          FULL_TAGS=""
          for tag in "${TAGS[@]}"; do
            FULL_TAGS+="${{ inputs.acr-registry }}/${{ inputs.acr-namespace }}/${{ inputs.image-name }}:${tag},"
          done
          # 去掉最后一个逗号
          FULL_TAGS=${FULL_TAGS%,}
          echo "full_tags=$FULL_TAGS" >> "$GITHUB_OUTPUT"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.dockerfile }}
          push: ${{ inputs.push }}
          tags: ${{ steps.tags.outputs.full_tags }}
          platforms: linux/amd64  # 可根据需要添加 linux/arm64 等

      # 可选的安全扫描功能
      - name: Build and save
        uses: docker/build-push-action@v3
        with:
          context: ./new-scan-engine
          tags: jackacr-registry.ap-northeast-1.cr.aliyuncs.com/jacknamespace/samplevotingapp_result
          load: true

      - name: Setup cache
        uses: actions/cache@v3
        with:
          path: cache
          key: ${{ runner.os }}-cache-${{ hashFiles('**/sysdig-cli-scanner', '**/latest_version.txt', '**/db/main.db.meta.json', '**/scanner-cache/inlineScannerCache.db') }}
          restore-keys: ${{ runner.os }}-cache-

      - name: Download sysdig-cli-scanner if needed
        run:  |
          curl -sLO https://download.sysdig.com/scanning/sysdig-cli-scanner/latest_version.txt
          mkdir -p ${GITHUB_WORKSPACE}/cache/db/
          if [ ! -f ${GITHUB_WORKSPACE}/cache/latest_version.txt ] || [ $(cat ./latest_version.txt) != $(cat ${GITHUB_WORKSPACE}/cache/latest_version.txt) ]; then
            cp ./latest_version.txt ${GITHUB_WORKSPACE}/cache/latest_version.txt
            curl -sL -o ${GITHUB_WORKSPACE}/cache/sysdig-cli-scanner "https://download.sysdig.com/scanning/bin/sysdig-cli-scanner/$(cat ${GITHUB_WORKSPACE}/cache/latest_version.txt)/linux/amd64/sysdig-cli-scanner"
            chmod +x ${GITHUB_WORKSPACE}/cache/sysdig-cli-scanner
          else
            echo "sysdig-cli-scanner latest version already downloaded"
          fi

      - name: Scan the image using sysdig-cli-scanner
        env:
          SECURE_API_TOKEN: ${{ secrets.SECURE_API_TOKEN }}
          IMAGE_NAME: ${{ inputs.image-name }}
        run: |
          ${GITHUB_WORKSPACE}/cache/sysdig-cli-scanner \
            --apiurl ${SYSDIG_SECURE_ENDPOINT} \
            docker://${{ inputs.acr-registry }}/${{ inputs.acr-namespace }}/${{ inputs.image-name }}
            --console-log \
            --dbpath=${GITHUB_WORKSPACE}/cache/db/ \
            --cachepath=${GITHUB_WORKSPACE}/cache/scanner-cache/
