# .github/workflows/reusable-docker-build-acr.yaml
name: Reusable Docker Build for ACR

on:
  workflow_call:
    inputs:
      image-name:
        description: 'samplevotingapp_result'
        required: true
        type: string
      tags:
        description: '（如 latest,v1.0）'
        required: false
        type: string
        default: 'latest'
      push:
        description: 'if push to ACR'
        required: false
        type: boolean
        default: false
      acr-registry:
        description: '阿里云 ACR 实例地址（如 registry.cn-hangzhou.aliyuncs.com）'
        required: true
        type: string
      acr-namespace:
        description: '阿里云 ACR 命名空间（通常是你的阿里云账号 ID 或自定义 namespace）'
        required: true
        type: string
      dockerfile:
        description: 'Dockerfile 路径（相对于仓库根目录）'
        required: false
        type: string
        default: './Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Alibaba Cloud ACR
        if: ${{ inputs.push }}
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.acr-registry }}
          username: ${{ secrets.ACR_REGISTRY_USER }}
          password: ${{ secrets.ACR_REGISTRY_PASSWORD }}

      - name: Prepare tags
        id: tags
        run: |
          IFS=',' read -ra TAGS <<< "${{ inputs.tags }}"
          FULL_TAGS=""
          for tag in "${TAGS[@]}"; do
            FULL_TAGS+="${{ inputs.acr-registry }}/${{ inputs.acr-namespace }}/${{ inputs.image-name }}:${tag},"
          done
          # 去掉最后一个逗号
          FULL_TAGS=${FULL_TAGS%,}
          echo "full_tags=$FULL_TAGS" >> "$GITHUB_OUTPUT"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ inputs.dockerfile }}
          push: ${{ inputs.push }}
          tags: ${{ steps.tags.outputs.full_tags }}
          platforms: linux/amd64  # 可根据需要添加 linux/arm64 等